name: ğŸ‘· CI

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144
  # Vitest auto retry on flaky segfault
  VITEST_SEGFAULT_RETRY: 3

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: "Build&Test: node-18, ubuntu-latest"
    steps:
      - name: â¤µï¸ Checkout
        uses: actions/checkout@v3
        with:
          # Assume PRs are less than 50 commits
          fetch-depth: 50

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@57d9664f8e2aa45f26bcb59095f99aa47ae8e90d # v35.4.4
        with:
          files: |
            docs/**
            .github/**
            !.github/workflows/ci.yml
            **.md

      - name: ğŸ‰ Install pnpm
        if: steps.changed-files.outputs.only_changed != 'true'
        uses: pnpm/action-setup@v2.2.4

      - name: ğŸ‰ Set node version to 18
        if: steps.changed-files.outputs.only_changed != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: ğŸš§ Install deps
        if: steps.changed-files.outputs.only_changed != 'true'
        run: pnpm install

      - name: ğŸ“¦ Build
        if: steps.changed-files.outputs.only_changed != 'true'
        run: pnpm run build

      - name: ğŸ”€ Test unit
        if: steps.changed-files.outputs.only_changed != 'true'
        run: pnpm run test

  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: "Lint: node-18, ubuntu-latest"
    steps:
      - name: â¤µï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ‰ Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: ğŸ‰ Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: ğŸš§ Install deps
        run: pnpm install

      - name: ğŸ“¦ Build
        run: pnpm run build

      - name: ğŸ”€ Lint
        run: pnpm run lint

      # From https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
      - name: ğŸ”€ Check workflow files
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=""
